#!/usr/bin/env python3
"""Run the Hedge ML/RL deterministic validation matrix in fail-fast order."""
# Standalone bootstrap runner import layout is intentionally stable.
# ruff: noqa: I001

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import tempfile
import time
import xml.etree.ElementTree as ET
from datetime import UTC, datetime
from pathlib import Path

ROUND_MODULES = {
    range(21, 31): "freqtrade/freqai/hedge_rl/contracts.py",
    range(31, 41): "freqtrade/freqai/hedge_rl/features.py",
    range(41, 51): "freqtrade/freqai/hedge_rl/market_data.py",
    range(51, 61): "freqtrade/freqai/hedge_rl/accounting.py",
    range(61, 71): "freqtrade/freqai/hedge_rl/execution_models.py",
    range(71, 81): "freqtrade/freqai/hedge_rl/reward_extensions.py",
    range(81, 91): "freqtrade/freqai/hedge_rl/env_extensions.py",
    range(91, 101): "freqtrade/freqai/hedge_rl/training_extensions.py",
}


def discover(source: Path) -> dict[int, str]:
    result: dict[int, str] = {}
    root = source / "tests/hedge/mlrl"
    for path in sorted(root.glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in tree.body:
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            match = re.fullmatch(r"test_round(\d+)_.*", node.name)
            if match is None:
                continue
            number = int(match.group(1))
            if 21 <= number <= 100:
                if number in result:
                    raise ValueError(f"duplicate ML/RL validation check {number}")
                result[number] = f"{path.relative_to(source).as_posix()}::{node.name}"
    expected = set(range(21, 101))
    if set(result) != expected:
        raise ValueError(
            f"ML/RL 80-round coverage mismatch: missing={sorted(expected - set(result))}, "
            f"unexpected={sorted(set(result) - expected)}"
        )
    return result


def module_for_round(number: int) -> str:
    for numbers, module in ROUND_MODULES.items():
        if number in numbers:
            return module
    raise ValueError(f"no implementation module registered for round {number}")


def run(source: Path) -> dict[str, object]:
    source = source.resolve()
    tests = discover(source)
    for module in sorted(set(ROUND_MODULES.values())):
        result = subprocess.run(
            [sys.executable, "-m", "py_compile", str(source / module)],
            cwd=source,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        if result.returncode != 0:
            return {
                "schema": "freqtrade-hedge-mlrl-validation-v1",
                "release": "clean-mainline",
                "status": "FAIL",
                "validation_checks_expected": 80,
                "validation_checks_executed": 0,
                "validation_checks_passed": 0,
                "compile_failure": {"module": module, "output": result.stdout[-8000:]},
                "results": [],
            }

    nodes = [tests[number] for number in range(21, 101)]
    with tempfile.TemporaryDirectory() as directory:
        junit = Path(directory) / "rounds.xml"
        started = time.perf_counter()
        process = subprocess.run(
            [
                sys.executable,
                "-m",
                "pytest",
                "-q",
                "-x",
                "-o",
                "addopts=",
                "--confcutdir",
                str(source / "tests/hedge/mlrl"),
                "--disable-warnings",
                "--tb=short",
                "--junitxml",
                str(junit),
                *nodes,
            ],
            cwd=source,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            check=False,
        )
        duration = time.perf_counter() - started
        if not junit.is_file():
            return {
                "schema": "freqtrade-hedge-mlrl-validation-v1",
                "release": "clean-mainline",
                "status": "FAIL",
                "validation_checks_expected": 80,
                "validation_checks_executed": 0,
                "validation_checks_passed": 0,
                "duration_seconds": round(duration, 6),
                "pytest_output": process.stdout[-16000:],
                "results": [],
            }
        # JUnit is generated by this process in a private temporary directory.
        cases = {
            case.attrib.get("name", ""): case
            for case in ET.parse(junit).getroot().iter("testcase")  # noqa: S314
        }
        results: list[dict[str, object]] = []
        for development_index, number in enumerate(range(21, 101), start=1):
            node = tests[number]
            case = cases.get(node.rsplit("::", 1)[1])
            if case is None:
                break
            issue = case.find("failure") or case.find("error") or case.find("skipped")
            passed = issue is None
            results.append(
                {
                    "round": number,
                    "development_index": development_index,
                    "test": node,
                    "module": module_for_round(number),
                    "compile_passed": True,
                    "test_passed": passed,
                    "passed": passed,
                    "duration_seconds": float(case.attrib.get("time", "0")),
                    "message": ""
                    if issue is None
                    else (issue.attrib.get("message") or issue.text or "")[-4000:],
                }
            )
            if not passed:
                break
    passed = process.returncode == 0 and len(results) == 80 and all(
        bool(item["passed"]) for item in results
    )
    return {
        "schema": "freqtrade-hedge-mlrl-validation-v1",
        "release": "clean-mainline",
        "started_at": datetime.now(UTC).isoformat(),
        "round_first": 21,
        "round_last": 100,
        "validation_checks_expected": 80,
        "validation_checks_executed": len(results),
        "validation_checks_passed": sum(bool(item["passed"]) for item in results),
        "duration_seconds": round(duration, 6),
        "status": "PASS" if passed else "FAIL",
        "pytest_output": process.stdout[-16000:],
        "results": results,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=Path.cwd())
    parser.add_argument("--json-out", type=Path)
    args = parser.parse_args(argv)
    report = run(args.source)
    payload = json.dumps(report, indent=2, ensure_ascii=False)
    print(payload)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(payload + "\n", encoding="utf-8")
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
